"""
    Library of predefined Frame used for DDS, ODF, MODF geenration
"""

DDS = {
    "150" : ["d_incl", "d_azimuth", "d_dip", "d_gmag", "d_hmag", "d_tf"],
    "160" : ["d_incl_hr", "d_azimuth_hr", "d_dip_hr", "d_gmag", "d_hmag", "d_tf"],
    "170" : ["d_incl_hr", "d_azimuth_hr", "d_dip_hr", "d_gmag", "d_hmag", "d_tf"]
}


MODF = {
    "ECOTOOL": {
        "5.3": [
            ["SUBMODFID", "Seq_APPO_v", "O_APPO_v", "O_APPO_v", "O_APPO_v", "O_APPO_v", "O_APPO_v", "O_APPO_v", "O_APPO_v", "O_APPO_v", "O_APPO_v", "O_APPO_v", "O_APPO_v", "O_APPO_v", "O_APPO_v", "O_APPO_v", "O_APPO_v", "O_APPO_v", "O_APPO_v", "O_APPO_v"],
            ["SUBMODFID", "Seq_APPO_v", "O_APPO_v", "O_APPO_v", "O_APPO_v", "O_APPO_v", "O_APPO_v", "O_APPO_v", "O_APPO_v", "O_APPO_v", "O_APPO_v", "O_APPO_v", "O_APPO_v", "O_APPO_v", "O_APPO_v", "O_APPO_v", "O_APPO_v", "O_APPO_v", "O_APPO_v", "O_APPO_v", "O_APPO_v", "O_APPO_v", "O_APPO_v", "O_APPO_v", "O_APPO_v"],
            ["SUBMODFID", "Seq_APPO_v", "O_APPO_v", "O_APPO_v", "O_APPO_v", "O_APPO_v", "O_APPO_v", "O_APPO_v", "O_APPO_v", "O_APPO_v", "O_APPO_v", "O_APPO_v", "O_APPO_v", "O_APPO_v", "O_APPO_v", "O_APPO_v", "O_APPO_v", "O_APPO_v", "O_APPO_v", "O_APPO_v", "O_APPO_v", "O_APPO_v", "O_APPO_v", "O_APPO_v", "O_APPO_v", "O_APPO_v", "O_APPO_v", "O_APPO_v", "O_APPO_v", "O_APPO_v", "O_APPO_v"],
            ["SUBMODFID", "Seq_APPO_v", "O_APPO_v", "O_APPO_v", "O_APPO_v", "O_APPO_v", "O_APPO_v", "O_APPO_v", "O_APPO_v", "O_APPO_v", "O_APPO_v", "O_APPO_v", "O_APPO_v", "O_APPO_v", "O_APPO_v", "O_APPO_v", "O_APPO_v", "O_APPO_v", "O_APPO_v", "O_APPO_v", "O_APPO_v", "O_APPO_v", "O_APPO_v", "O_APPO_v", "O_APPO_v", "O_APPO_v", "O_APPO_v", "O_APPO_v", "O_APPO_v", "O_APPO_v", "O_APPO_v", "O_APPO_v", "O_APPO_v", "O_APPO_v", "O_APPO_v", "O_APPO_v"],
            ["SUBMODFID", "Seq_APPO_v", "O_APPO_v", "O_APPO_v", "O_APPO_v", "O_APPO_v", "O_APPO_v", "O_APPO_v", "O_APPO_v", "O_APPO_v", "O_APPO_v", "O_APPO_v", "O_APPO_v", "O_APPO_v", "O_APPO_v", "O_APPO_v", "O_APPO_v", "O_APPO_v", "O_APPO_v", "O_APPO_v", "O_APPO_v", "O_APPO_v", "O_APPO_v", "O_APPO_v", "O_APPO_v", "O_APPO_v", "O_APPO_v", "O_APPO_v", "O_APPO_v", "O_APPO_v", "O_APPO_v", "O_APPO_v", "O_APPO_v", "O_APPO_v", "O_APPO_v", "O_APPO_v", "O_APPO_v", "O_APPO_v", "O_APPO_v", "O_APPO_v", "O_APPO_v", "O_APPO_v", "O_APPO_v", "O_APPO_v"]
        ],
        "7.1": [
            ["SUBMODFID", "Seq_APPO_v", "TS_APPO_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v"],
            ["SUBMODFID", "Seq_APPO_v", "TS_APPO_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v"],
            ["SUBMODFID", "Seq_APPO_v", "TS_APPO_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v"],
            ["SUBMODFID", "Seq_APPO_v", "TS_APPO_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v"],
            ["SUBMODFID", "Seq_APPO_v", "TS_APPO_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v"],
            ["SUBMODFID", "Seq_APPO_v", "TS_APPO_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v"]
        ],
        "8.0": [
            ["SUBMODFID", "Seq_APPO_v", "TS_APPO_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v"],
            ["SUBMODFID", "Seq_APPO_v", "TS_APPO_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v"],
            ["SUBMODFID", "Seq_APPO_v", "TS_APPO_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v"],
            ["SUBMODFID", "Seq_APPO_v", "TS_APPO_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v"],
            ["SUBMODFID", "Seq_APPO_v", "TS_APPO_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v"],
            ["SUBMODFID", "Seq_APPO_v", "TS_APPO_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v", "O_APPO2_v"]
        ]
    },
    "ARC6TOOL": {
        "9.7": [
            ["SUBMODFID", "Seq_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c"],
            ["SUBMODFID", "Seq_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c"],
            ["SUBMODFID", "Seq_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c"],
            ["SUBMODFID", "Seq_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c"],
            ["SUBMODFID", "Seq_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c"]
        ],
        "9.9": [
            ["SUBMODFID", "Seq_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c"],
            ["SUBMODFID", "Seq_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c"],
            ["SUBMODFID", "Seq_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c"],
            ["SUBMODFID", "Seq_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c"],
            ["SUBMODFID", "Seq_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c", "O_APPO_c"]
        ]
    }
}

ODF = {
    "IMPTOOL": {
        "160": ["LTBToolID", "survey_cnt_ck"]
    },
    "FPWDTOOL": {
        "8.2": ["LTBToolID", "A_ODFPWD_p", "A_ODFPWD_p", "A_ODFPWD_p", "A_ODFPWD_p", "GEN4_p", "A_ODFPWD_p", "A_ODFPWD_p", "A_ODFPWD_p", "A_ODFPWD_p", "GEN6_p", "A_ODFPWD_p", "A_ODFPWD_p", "A_ODFPWD_p", "A_ODFPWD_p", "HYDR_RET_p", "A_ODFPWD_p", "A_ODFPWD_p", "A_ODFPWD_p", "A_ODFPWD_p"],
        "8.7": ["LTBToolID", "A_ODFPWD_p", "A_ODFPWD_p", "A_ODFPWD_p", "A_ODFPWD_p", "GEN4_p", "A_ODFPWD_p", "A_ODFPWD_p", "A_ODFPWD_p", "A_ODFPWD_p", "GEN6_p", "A_ODFPWD_p", "A_ODFPWD_p", "A_ODFPWD_p", "A_ODFPWD_p", "HYDR_RET_p", "A_ODFPWD_p", "A_ODFPWD_p", "A_ODFPWD_p", "A_ODFPWD_p"]
    }, 
    "FPD4TOOL": {
        "2.4": ["LTBToolID", "A_ODFPWD4_p4", "A_ODFPWD4_p4", "A_ODFPWD4_p4", "A_ODFPWD4_p4", "HYDR_SET_p4", "A_ODFPWD4_p4", "A_ODFPWD4_p4", "A_ODFPWD4_p4", "A_ODFPWD4_p4", "HYDR_TURN_p4", "A_ODFPWD4_p4", "A_ODFPWD4_p4", "A_ODFPWD4_p4", "A_ODFPWD4_p4", "HYDR_RET_p4", "A_ODFPWD4_p4", "A_ODFPWD4_p4", "A_ODFPWD4_p4", "A_ODFPWD4_p4", "STATE_MACH_p4"],
        "2.5": ["LTBToolID", "A_ODFPWD4_p4", "A_ODFPWD4_p4", "A_ODFPWD4_p4", "A_ODFPWD4_p4", "HYDR_SET_p4", "A_ODFPWD4_p4", "A_ODFPWD4_p4", "A_ODFPWD4_p4", "A_ODFPWD4_p4", "HYDR_TURN_p4", "A_ODFPWD4_p4", "A_ODFPWD4_p4", "A_ODFPWD4_p4", "A_ODFPWD4_p4", "HYDR_RET_p4", "A_ODFPWD4_p4", "A_ODFPWD4_p4", "A_ODFPWD4_p4", "A_ODFPWD4_p4", "STATE_MACH_p4"]
    }, 
    "GDISTOOL": {
        "2.1": ["LTBToolID", "ACQ_DELAY_gdi", "NFSTAT_gdi", "INCL_N_gdi", "AZIM_N_gdi", "LAT_N_gdi", "TOTALW_wr_gdi", "ST_ITF_gdi", "TEMP_N_gdi", "QISG_AZIM_gdi", "GOODSVYCNT_gdi", "SVYCNT_gdi", "ITFSTAT_gdi", "GDI_MODE_gdi", "QISG_SITF_gdi", "TOTALG_N_gdi"],
        "3.0": ["LTBToolID", "ACQ_DELAY_gdi", "NFSTAT_gdi", "INCL_N_gdi", "AZIM_N_gdi", "LAT_N_gdi", "TOTALW_wr_gdi", "ST_ITF_gdi", "TEMP_N_gdi", "QISG_AZIM_gdi", "GOODSVYCNT_gdi", "SVYCNT_gdi", "ITFSTAT_gdi", "GDI_MODE_gdi", "QISG_SITF_gdi", "TOTALG_N_gdi"],
        "4.0": ["LTBToolID", "ACQ_DELAY_gdi", "NFSTAT_gdi", "INCL_N_gdi", "AZIM_N_gdi", "LAT_N_gdi", "TOTALW_wr_gdi", "ST_ITF_gdi", "TEMP_N_gdi", "QISG_AZIM_gdi", "GOODSVYCNT_gdi", "SVYCNT_gdi", "ITFSTAT_gdi", "GDI_MODE_gdi", "QISG_SITF_gdi", "TOTALG_N_gdi"],
        "5.1": ["LTBToolID", "ACQ_DELAY_gdi", "NFSTAT_gdi", "INCL_N_gdi", "AZIM_N_gdi", "LAT_N_gdi", "TOTALW_wr_gdi", "ST_ITF_gdi", "TEMP_N_gdi", "QISG_AZIM_gdi", "GOODSVYCNT_gdi", "SVYCNT_gdi", "ITFSTAT_gdi", "GDI_MODE_gdi", "QISG_SITF_gdi", "TOTALG_N_gdi"],
        "6.0": ["LTBToolID", "ACQ_DELAY_gdi", "NFSTAT_gdi", "INCL_N_gdi", "AZIM_N_gdi", "LAT_N_gdi", "TOTALW_wr_gdi", "ST_ITF_gdi", "TEMP_N_gdi", "QISG_AZIM_gdi", "GOODSVYCNT_gdi", "SVYCNT_gdi", "ITFSTAT_gdi", "GDI_MODE_gdi", "QISG_SITF_gdi", "TOTALG_N_gdi"],
        "6.1": ["LTBToolID", "ACQ_DELAY_gdi", "NFSTAT_gdi", "INCL_N_gdi", "AZIM_N_gdi", "LAT_N_gdi", "TOTALW_wr_gdi", "ST_ITF_gdi", "TEMP_N_gdi", "QISG_AZIM_gdi", "GOODSVYCNT_gdi", "SVYCNT_gdi", "ITFSTAT_gdi", "GDI_MODE_gdi", "QISG_SITF_gdi", "TOTALG_N_gdi"]
    }
}
